### PR TITLE
using Chrome.Cookies api to get SID, which requires to be in Backgrou…

### PR DESCRIPTION
**Pull request by shintynash**
…nd.JS

TBH, this the first time I have commited in GitHUB and done a pull request! Please let me know if I did anything funky

Andrew

### CODE REVIEW

**Comment by 0cv** [comment]
Thanks Andrew. Only funky thing I can see now is the mix of tabs and whitespaces (need an .editorconfig anyway). I will have a deeper look in the code later but seems you nailed it, though I would take the occasion to get the cookie from the salesforce.com domain instead of the force.com so that we can skip any redirection.

**Comment by shintynash** [comment]
not sure how we can map the lightning or force.com domain to the appropriate salesforce.com one? I guess we could search through all the SID cookies with salesforce.com and match the prefix, but will need to consider the structure for sandboxes and managed package visualforce pages, so it will get a bit messy. Is there something a bit simpler that I have missed?

**Comment by 0cv** [comment]
That's right, I would be looking for something like `if (cookie.domain.indexOf('.salesforce.com') > -1 && cookie.domain.indexOf(orgName) > -1) {...}` with orgName being something like `sender.url.split('.')[0].replace('https://', '');`, which shall work both for org without custom domain name (e.g. `cs16`, or with custom domain e.g. `myorg.my.salesforce.com` - not sure if that's enough for Visualforce though but I guess a logic could be built around it.

**Comment by shintynash** [comment]
I was thinking something along those lines, there are just quite a few different scenarios to consider.

For custom domain names in lightning, we need to be careful of sandbox environments. We could accidentally pick up the sandbox SID rather than the production one:
CustomDomain--Sandbox.instance.my.salesforce.com would hit a match with the CustomDomain from the production org

Also irritatingly with VF pages it gets even worse when trying to determine the custom domain name:
CustomDomain--c.instance.visual.force.com
CustomDomain--Sandbox--c.instance.visual.force.com

 and within packages
CustomDomain--Package.instance.visual.force.com
CustomDomain--Sandbox--Package.instance.visual.force.com


I don't actually know what a managed package in a production org without any custom domain would actually look like but based on a sandbox I would expect:
Package.instance.visual.force.com

While I'm sure we can come up with logic to fit all these scenarios, my concern is if I have missed any scenarios.

CustomDomain.lightning.force.com
CustomDomain--Sandbox.lightning.force.com

CustomDomain--c.instance.visual.force.com
CustomDomain--Sandbox--c.instance.visual.force.com
CustomDomain--Package.instance.visual.force.com
CustomDomain--Sandbox--Package.instance.visual.force.com

c.instance.visual.force.com
Package.instance.visual.force.com

Any other scenarios you are aware of?

And we are trying to find the matching cookie with domain

CustomDomain.my.salesforce.com
CustomDomain--Sandbox.instance.my.salesforce.com
instance.salesforce.com

**Comment by 0cv** [comment]
Well, you're right, it might be complicated... and breaks when Salesforce changes something. A better idea may be to still look for the '.salesforce.com' domain but instead of trying to match the right domain, we could look at the value of the `sid` which includes the unique Org Id. The org id corresponds to the 15 first digit of the `sid`, or everything before the exclamation mark `!`. I think it would be a more bullet proofed solution.

**Comment by shintynash** [comment]
that sounds like a great idea, I hadn't noticed that!

**Comment by shintynash** [comment]
Hows that then, updated to find the salesforce.com domain, no more loading new tabs and switching back and forth with lightning experience.

**Comment by 0cv** [comment]
Brilliant thanks! I will have a look latest early next week

**Pull request merged**
